### ISSUE TITLE
Startsida Mobil

### ISSUE THREAD

**Issue by gabrielkereklidispaulin** [chas-academy/u01-designstudie-bluewave#1]
Create content for the startsida.  EDIT

A small description about the studios and what else there is to find. 
Pictures: some pictures that looks like someone else has taken. some pictures of the studios and other areas

**Comment by gabrielkereklidispaulin** [comment]
Kommer finnas utmaningar med att lösa formateringen mellan desktop och mobil där mobil ofta följer en scrollande logik och desktop är mer klicka sig fram!

**Comment by Chokladglasyr** [comment]
@FredricLaestander 
gjorde en scroll variant på sin övningsuppgift, till desktop men går väl att implementera på en mobil frame. Jag upplever att det är pga den avsmalnande designen som ger en scrollande logik till mobil frame. Om jag förstod utmaningarna rätt. får väl se när vi skapar designen.
