### ISSUE TITLE
Samla bilder

### ISSUE THREAD

**Issue by gabrielkereklidispaulin** [chas-academy/u01-designstudie-bluewave#13]
Pics of the space, the studios, Medlemslista (3 headshots of "the founders" of PixelCraft Studios).

**Comment by gabrielkereklidispaulin** [comment]
Görs gemensamt tillsammans

**Comment by Chokladglasyr** [comment]
https://drive.google.com/drive/folders/1owvDBU9kO_GOKBsg_HaEKdHXPuO4TJ7p

**Comment by AnnaKirs** [comment]
I have updated the Google Drive with more photos. Let's agree on a time to choose the photos we want to use.
