### ISSUE TITLE
Intervjumall

### ISSUE THREAD

**Issue by gabrielkereklidispaulin** [chas-academy/u01-designstudie-bluewave#8]
Create a template for the interviews

**Comment by AnnaKirs** [comment]
Anna has 2 interviewees that have agreed: **Josef J.** (pro hobby) & **Erica G.** (freelance). Awaiting for 3rd person to respond: **Kim** (pro freelance with lots of experience).

**Comment by Chokladglasyr** [comment]
Waiting for the monday föreläsning where we are going to get more information on what we want to get out from an interview.

**Comment by FredricLaestander** [comment]
Fredric have 1 interview on standby for thursday/friday.
